# Generated by Django 6.0.5 on 2026-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='amount_inr',
            field=models.DecimalField(decimal_places=2, default=499.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
