# Generated by Django 6.0.5 on 2026-05-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicebooking_amount_inr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
