# Generated by Django 6.0.5 on 2026-05-30 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=10)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('budget_range', models.CharField(choices=[('basic', 'Basic (under 15,000 INR)'), ('standard', 'Standard (15,000 - 50,000 INR)'), ('premium', 'Premium (50,000 - 1,50,000 INR)'), ('enterprise', 'Enterprise (above 1,50,000 INR)')], default='standard', max_length=20)),
                ('preferred_platform', models.CharField(choices=[('website', 'Website'), ('web_app', 'Web Application'), ('mobile_ready', 'Mobile-ready Web App')], default='website', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('proposal_sent', 'Proposal Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
