# Generated by Django 6.0.5 on 2026-06-03 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_examquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMockAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('auto_submitted', models.BooleanField(default=False)),
                ('auto_submit_reason', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='institute.exammock')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_mock_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at',),
            },
        ),
    ]
