# Generated by Django 6.0.5 on 2026-06-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_exammockattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=160)),
                ('course_name', models.CharField(blank=True, max_length=180)),
                ('exam_type', models.CharField(choices=[('eapcet', 'EAPCET'), ('jee_mains', 'JEE Mains'), ('placement', 'Placed Students'), ('other', 'Other Achievements')], default='other', max_length=20)),
                ('rank_label', models.CharField(blank=True, help_text='Examples: AIR 120, State Rank 45, Top 500', max_length=120)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('review', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='institute/students/')),
                ('image_url', models.URLField(blank=True)),
                ('show_on_home', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('exam_type', 'display_order', 'student_name'),
            },
        ),
    ]
