# Generated by Django 6.0.5 on 2026-06-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_studentachievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentachievement',
            name='education',
            field=models.CharField(blank=True, help_text='Example: B.Tech CSE, Intermediate MPC', max_length=180),
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='htno',
            field=models.CharField(blank=True, help_text='Hall ticket number or student ID', max_length=80),
        ),
    ]
