# Generated by Django 6.0.5 on 2026-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_studentachievement_education_studentachievement_htno'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='diagram_image',
            field=models.FileField(blank=True, help_text='Optional chemistry/organic structure diagram image for this question.', upload_to='institute/question_diagrams/'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='diagram_image_url',
            field=models.URLField(blank=True, help_text='Optional external diagram URL if you do not upload an image.'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question_text',
            field=models.TextField(help_text='Supports LaTeX. Use $...$ for inline and $$...$$ for block equations. For chemistry, use mhchem notation like \\ce{H2O}; structural diagrams such as benzene rings need an image or a chemistry-specific renderer.'),
        ),
    ]
